=== Netivski/projectoseminario/trunk/Esquiços/Definição Dicionário Dados/XMLTipos/XSDTipos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by Ricardo Neto (Netpat) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="types">
		<xs:annotation>
			<xs:documentation>Root element of the type system file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>

				<!--  <begin> -->
				<!-- baseTypes -->
				<xs:element name="baseTypes">
				
					<xs:annotation>
						<xs:documentation>Element that serves as a collection for all base types</xs:documentation>
					</xs:annotation>
					
					<xs:complexType>
						<xs:sequence>
							<xs:element name="baseType" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Element that represents a base type</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="precision" type="xs:int" use="required"/>
									<xs:attribute name="scale" type="xs:int" use="required"/>
									<xs:attribute name="maxLength" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					
					<xs:key name="key_typeName">
						<xs:annotation>
							<xs:documentation>Definition of attribute 'name' as a "primary key" of baseType element</xs:documentation>
						</xs:annotation>
						<xs:selector xpath="baseType"/>
						<xs:field xpath="@name"/>
					</xs:key>
					
				</xs:element>
				<!-- baseTypes -->
				<!--  <end> -->


				<!--  <begin> -->
				<!-- customTypes -->
				<xs:element name="customTypes">
				
					<xs:annotation>
						<xs:documentation>Element that wil gather all custom types</xs:documentation>
					</xs:annotation>
					
					<xs:complexType>
						<xs:sequence>
							<xs:element name="customType" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Element that represents a custom type</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="minValue" minOccurs="0"  maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="value" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="maxValue" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="value" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="type" type="xs:string" use="required"/>
									<xs:attribute name="precision" type="xs:int" use="optional"/>
									<xs:attribute name="scale" type="xs:int" use="optional"/>
									<xs:attribute name="maxLength" type="xs:int" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>

					<xs:unique name="un_customType_name">
						<xs:annotation>
							<xs:documentation>Definition of attribute 'name' as a "primary key" of customType element</xs:documentation>
						</xs:annotation>
						<xs:selector xpath="customType"/>
						<xs:field xpath="@name"/>
					</xs:unique>
				
				</xs:element>
				<!-- customTypes -->
				<!--  <end> -->

			</xs:sequence>
		</xs:complexType>
			
		<xs:keyref refer="key_typeName" name="fk_baseType">
			<xs:annotation>
				<xs:documentation>Definition of attribute 'name' as a "foreign key", referencing attribute 'name' of 'baseType' elements defined</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="customTypes/customType"/>
			<xs:field xpath="@type"/>
		</xs:keyref>
		
	</xs:element>
</xs:schema>

=== Netivski/projectoseminario/trunk/Src/3D/tipos/Ideias Abandonadas/XMLTipos.xml
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\XSDTipos.xsd">
	<baseTypes>
		<baseType name="binary" maxLength="8000" precision="0" scale="0"/>
		<baseType name="boolean" maxLength="1" precision="1" scale="0"/>
		<baseType name="datetime" maxLength="8" precision="23" scale="3"/>
		<baseType name="decimal" maxLength="17" precision="38" scale="38"/>
		<baseType name="double" maxLength="4" precision="24" scale="0"/>
		<baseType name="float" maxLength="8" precision="53" scale="0"/>
		<baseType name="string" maxLength="8000" precision="0" scale="0"/>
		<baseType name="int" maxLength="4" precision="10" scale="0"/>
		<baseType name="long" maxLength="8" precision="19" scale="0"/>

		<baseType name="guid" maxLength="16" precision="0" scale="0"/>
		<baseType name="char" maxLength="8000" precision="0" scale="0"/>
	</baseTypes>
	<customTypes>
		<customType name="nif" type="string">
			<minValue value="100000000"/>
			<maxValue value="999999999"/>
		</customType>
	</customTypes>
</types>
