=== Netivski/projectoseminario/trunk/Esquiços/Definição Dicionário Dados/XMLTipos/XSDTiposBase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by Ricardo Neto (Netpat) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="baseTypes">
		<xs:annotation>
			<xs:documentation>Element that serves as a collection for all base types</xs:documentation>
		</xs:annotation>
		<xs:complexType/>
	</xs:element>
	<xs:element name="baseType">
		<xs:annotation>
			<xs:documentation>Element that represents a base type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="precision" type="xs:int" use="required"/>
			<xs:attribute name="scale" type="xs:int" use="required"/>
			<xs:attribute name="maxLength" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Netivski/projectoseminario/trunk/Temp/XMLTiposBase.xml
<baseTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\XSDTiposBase.xsd">
  <baseType name="guid" maxLength="16" precision="0" scale="0"/>
	<baseType name="datetime" maxLength="8" precision="23" scale="3"/>
	<baseType name="int" maxLength="4" precision="10" scale="0"/>
	<baseType name="long" maxLength="8" precision="19" scale="0"/>
	<baseType name="double" maxLength="4" precision="24" scale="0"/>
	<baseType name="float" maxLength="8" precision="53" scale="0"/>
	<baseType name="decimal" maxLength="17" precision="38" scale="38"/>
	<baseType name="boolean" maxLength="1" precision="1" scale="0"/>
	<baseType name="string" maxLength="8000" precision="0" scale="0"/>
	<baseType name="binary" maxLength="8000" precision="0" scale="0"/>
	<baseType name="char" maxLength="8000" precision="0" scale="0"/>
</baseTypes>
